name: Publish Docker

on:
  release:
    types: [published]
  push:
    tags: ['*']
    # branches: [master]
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
jobs:
  build_and_push:
    name: Build and Push
    runs-on: ["self-hosted", "linux", "x64", "ubuntu-latest"]
    env:
      ECR_REPO: 305587085711.dkr.ecr.us-west-2.amazonaws.com/darkforest-backend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
          token: ${{ secrets.GIT_CREDENTIALS }}
          ref: ${{ inputs.tag }}

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 305587085711.dkr.ecr.us-west-2.amazonaws.com
          username: ${{ secrets.ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_ACCESS_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: docker-builder
        uses: docker/setup-buildx-action@v2

      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_CREDENTIALS }}@github.com

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.ECR_REPO }}
          tags: |
            type=raw,value={{sha}}
            type=raw,value={{branch}}-{{sha}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value={{tag}}
            type=raw,value=${{ inputs.tag }}

      - name: Build and push images
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          cache-from: |
            type=registry,ref=${{ env.ECR_REPO }}:builder
            type=local,src=/tmp/buildx-cache-cross-step
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Update registry cache
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          builder: ${{ steps.docker-builder.outputs.name }}
          cache-from: |
            type=registry,ref=${{ env.ECR_REPO }}:builder
            type=local,src=/tmp/buildx-cache-cross-step
          cache-to: |
            type=registry,ref=${{ env.ECR_REPO }}:builder,mode=max
